"""polars-statistics: Statistical testing and regression for Polars DataFrames."""

from pathlib import Path

# Import expression API
from polars_statistics import exprs

# Import Rust bindings
from polars_statistics._polars_statistics import (
    # Augmented Linear Model
    ALM,
    ARD,
    BLS,
    GLMM,
    # Streaming & Online
    LARS,
    # Linear models
    OLS,
    PLS,
    RANSAC,
    RLS,
    WLS,
    # Demand Classification
    Aid,
    AidResult,
    BayesianRidge,
    BrownForsythe,
    BrunnerMunzel,
    CircularBlockBootstrap,
    Cloglog,
    DAgostino,
    ElasticNet,
    # GLM models
    Gamma,
    Huber,
    Isotonic,
    KruskalWallis,
    # Dynamic Linear Model
    LmDynamic,
    Logistic,
    LogisticRegression,
    # Non-Parametric Tests
    MannWhitneyU,
    MomentAccumulator,
    NegativeBinomial,
    PassiveAggressive,
    Poisson,
    Probit,
    # Smoothers
    PSpline,
    # Robust regression
    Quantile,
    Ridge,
    # Distributional Tests
    ShapiroWilk,
    # Bootstrap
    StationaryBootstrap,
    # Robust & sklearn-style solvers
    TheilSen,
    # Parametric Tests
    TTestInd,
    TTestPaired,
    Tweedie,
    WilcoxonSignedRank,
    YuenTest,
)
from polars_statistics.exprs import (
    # AID and Dynamic Linear Model expressions
    aid,
    aid_anomalies,
    alm,
    alm_formula,
    alm_formula_predict,
    alm_formula_summary,
    alm_predict,
    alm_summary,
    # Categorical tests
    binom_test,
    bls,
    bls_formula,
    bls_predict,
    bls_summary,
    brown_forsythe,
    brunner_munzel,
    check_binary_separation,
    check_count_sparsity,
    chisq_goodness_of_fit,
    chisq_test,
    clark_west,
    cloglog,
    cloglog_formula,
    cloglog_predict,
    cloglog_summary,
    cohen_kappa,
    # Diagnostics expressions
    condition_number,
    contingency_coef,
    cooks_distance,
    cramers_v,
    dagostino,
    dffits,
    # Forecast tests
    diebold_mariano,
    distance_cor,
    elastic_net,
    elastic_net_formula,
    elastic_net_formula_predict,
    elastic_net_formula_summary,
    elastic_net_predict,
    elastic_net_summary,
    # Modern tests
    energy_distance,
    energy_distance_nd,
    expanding_ols,
    externally_studentized_residuals,
    fisher_exact,
    g_test,
    gamma_dispersion_deviance,
    gamma_dispersion_pearson,
    gamma_pearson_chi_squared,
    gamma_standardized_deviance_residuals,
    gamma_standardized_pearson_residuals,
    generalized_vif,
    high_leverage_points,
    high_vif_predictors,
    huber,
    icc,
    influential_cooks,
    influential_dffits,
    isotonic,
    isotonic_predict,
    kendall,
    kruskal_wallis,
    lasso,
    lasso_formula,
    lasso_formula_predict,
    lasso_formula_summary,
    lasso_predict,
    lasso_summary,
    leverage,
    lm_dynamic,
    lm_dynamic_predict,
    # GLM expressions
    logistic,
    logistic_deviance_residuals,
    logistic_formula,
    logistic_formula_predict,
    logistic_formula_summary,
    logistic_pearson_residuals,
    logistic_predict,
    logistic_regression,
    logistic_summary,
    logistic_working_residuals,
    # Non-parametric tests
    mann_whitney_u,
    mcnemar_exact,
    mcnemar_test,
    mmd_test,
    model_confidence_set,
    mspe_adjusted,
    negative_binomial,
    negative_binomial_formula,
    negative_binomial_predict,
    negative_binomial_summary,
    nnls,
    nnls_formula,
    nnls_predict,
    # Regression expressions
    ols,
    # Formula-based regression expressions
    ols_formula,
    # Formula-based prediction expressions
    ols_formula_predict,
    # Formula-based summary expressions
    ols_formula_summary,
    # Prediction expressions
    ols_predict,
    # Summary expressions
    ols_summary,
    one_way_anova,
    partial_cor,
    # Correlation tests
    pearson,
    pearson_chi_squared_logistic,
    pearson_chi_squared_poisson,
    permutation_t_test,
    phi_coefficient,
    pls,
    poisson,
    poisson_deviance_residuals,
    poisson_formula,
    poisson_formula_predict,
    poisson_formula_summary,
    poisson_pearson_residuals,
    poisson_predict,
    poisson_summary,
    poisson_working_residuals,
    probit,
    probit_formula,
    probit_predict,
    probit_summary,
    prop_test_one,
    prop_test_two,
    quantile,
    quantile_predict,
    # Summary / predict completeness (issue #18)
    quantile_summary,
    repeated_measures_anova,
    residual_outliers,
    ridge,
    ridge_formula,
    ridge_formula_predict,
    ridge_formula_summary,
    ridge_predict,
    ridge_summary,
    rls,
    rls_formula,
    rls_predict,
    rls_summary,
    semi_partial_cor,
    # Distributional tests
    shapiro_wilk,
    spa_test,
    spearman,
    standardized_residuals,
    studentized_residuals,
    tost_bootstrap,
    tost_correlation,
    tost_prop_one,
    tost_prop_two,
    # TOST equivalence tests
    tost_t_test_one_sample,
    tost_t_test_paired,
    tost_t_test_two_sample,
    tost_wilcoxon_paired,
    tost_wilcoxon_two_sample,
    tost_yuen,
    # Parametric tests
    ttest_ind,
    ttest_paired,
    tweedie,
    tweedie_formula,
    tweedie_predict,
    tweedie_summary,
    two_way_anova,
    vif,
    wilcoxon_signed_rank,
    wls,
    wls_formula,
    wls_predict,
    wls_summary,
    yuen_test,
)

# Result-ergonomics helpers for the expression (Struct-column) surface
from polars_statistics.results import struct_to_dict, unnest

__version__ = "0.6.0"

# Library path for plugin registration
LIB = Path(__file__).parent

__all__ = [
    # Linear Models
    "OLS",
    "Ridge",
    "ElasticNet",
    "WLS",
    "RLS",
    "BLS",
    # Robust Regression Models
    "Quantile",
    "Isotonic",
    "Huber",
    "PLS",
    # Robust & sklearn-style solvers
    "TheilSen",
    "RANSAC",
    "BayesianRidge",
    "ARD",
    # Streaming & Online
    "LARS",
    "PassiveAggressive",
    "MomentAccumulator",
    # Smoothers
    "PSpline",
    # GLM Models
    "Gamma",
    "GLMM",
    "Logistic",
    "LogisticRegression",
    "Poisson",
    "NegativeBinomial",
    "Tweedie",
    "Probit",
    "Cloglog",
    # Augmented Linear Model
    "ALM",
    # Dynamic Linear Model
    "LmDynamic",
    # Demand Classification
    "Aid",
    "AidResult",
    # Bootstrap
    "StationaryBootstrap",
    "CircularBlockBootstrap",
    # Parametric Test Models
    "TTestInd",
    "TTestPaired",
    "BrownForsythe",
    "YuenTest",
    # Non-Parametric Test Models
    "MannWhitneyU",
    "WilcoxonSignedRank",
    "KruskalWallis",
    "BrunnerMunzel",
    # Distributional Test Models
    "ShapiroWilk",
    "DAgostino",
    # Expression API module
    "exprs",
    # Parametric test expressions
    "ttest_ind",
    "ttest_paired",
    "brown_forsythe",
    "yuen_test",
    "one_way_anova",
    "two_way_anova",
    "repeated_measures_anova",
    # Non-parametric test expressions
    "mann_whitney_u",
    "wilcoxon_signed_rank",
    "kruskal_wallis",
    "brunner_munzel",
    # Distributional test expressions
    "shapiro_wilk",
    "dagostino",
    # Forecast test expressions
    "diebold_mariano",
    "permutation_t_test",
    "clark_west",
    "spa_test",
    "model_confidence_set",
    "mspe_adjusted",
    # Modern test expressions
    "energy_distance",
    "energy_distance_nd",
    "mmd_test",
    # TOST equivalence test expressions
    "tost_t_test_one_sample",
    "tost_t_test_two_sample",
    "tost_t_test_paired",
    "tost_correlation",
    "tost_prop_one",
    "tost_prop_two",
    "tost_wilcoxon_paired",
    "tost_wilcoxon_two_sample",
    "tost_bootstrap",
    "tost_yuen",
    # Correlation test expressions
    "pearson",
    "spearman",
    "kendall",
    "distance_cor",
    "partial_cor",
    "semi_partial_cor",
    "icc",
    # Categorical test expressions
    "binom_test",
    "prop_test_one",
    "prop_test_two",
    "chisq_test",
    "chisq_goodness_of_fit",
    "g_test",
    "fisher_exact",
    "mcnemar_test",
    "mcnemar_exact",
    "cohen_kappa",
    "cramers_v",
    "phi_coefficient",
    "contingency_coef",
    # Regression expressions
    "ols",
    "ridge",
    "elastic_net",
    "lasso",
    "wls",
    "rls",
    "expanding_ols",
    "bls",
    "nnls",
    "quantile",
    "isotonic",
    "huber",
    "pls",
    # Diagnostics expressions
    "condition_number",
    "check_binary_separation",
    "check_count_sparsity",
    "vif",
    "leverage",
    "cooks_distance",
    "standardized_residuals",
    "studentized_residuals",
    "externally_studentized_residuals",
    "residual_outliers",
    "dffits",
    "influential_cooks",
    "influential_dffits",
    "high_leverage_points",
    "high_vif_predictors",
    "generalized_vif",
    "pearson_chi_squared_logistic",
    "pearson_chi_squared_poisson",
    "logistic_pearson_residuals",
    "logistic_deviance_residuals",
    "logistic_working_residuals",
    "poisson_pearson_residuals",
    "poisson_deviance_residuals",
    "poisson_working_residuals",
    "gamma_dispersion_deviance",
    "gamma_dispersion_pearson",
    "gamma_pearson_chi_squared",
    "gamma_standardized_pearson_residuals",
    "gamma_standardized_deviance_residuals",
    # GLM expressions
    "logistic",
    "logistic_regression",
    "poisson",
    "negative_binomial",
    "tweedie",
    "probit",
    "cloglog",
    "alm",
    # Summary expressions
    "ols_summary",
    "ridge_summary",
    "elastic_net_summary",
    "lasso_summary",
    "wls_summary",
    "rls_summary",
    "bls_summary",
    "logistic_summary",
    "poisson_summary",
    "negative_binomial_summary",
    "tweedie_summary",
    "probit_summary",
    "cloglog_summary",
    "alm_summary",
    # Prediction expressions
    "ols_predict",
    "ridge_predict",
    "elastic_net_predict",
    "lasso_predict",
    "wls_predict",
    "rls_predict",
    "bls_predict",
    "nnls_predict",
    "logistic_predict",
    "poisson_predict",
    "negative_binomial_predict",
    "tweedie_predict",
    "probit_predict",
    "cloglog_predict",
    "alm_predict",
    # Formula-based regression expressions
    "ols_formula",
    "ridge_formula",
    "elastic_net_formula",
    "lasso_formula",
    "wls_formula",
    "rls_formula",
    "bls_formula",
    "nnls_formula",
    "logistic_formula",
    "poisson_formula",
    "negative_binomial_formula",
    "tweedie_formula",
    "probit_formula",
    "cloglog_formula",
    "alm_formula",
    # Formula-based summary expressions
    "ols_formula_summary",
    "ridge_formula_summary",
    "elastic_net_formula_summary",
    "lasso_formula_summary",
    "logistic_formula_summary",
    "poisson_formula_summary",
    "alm_formula_summary",
    # Formula-based prediction expressions
    "ols_formula_predict",
    "ridge_formula_predict",
    "elastic_net_formula_predict",
    "lasso_formula_predict",
    "logistic_formula_predict",
    "poisson_formula_predict",
    "alm_formula_predict",
    # AID and Dynamic Linear Model expressions
    "aid",
    "aid_anomalies",
    "lm_dynamic",
    # Summary / predict completeness (issue #18)
    "quantile_summary",
    "quantile_predict",
    "isotonic_predict",
    "lm_dynamic_predict",
    # Result-ergonomics helpers (expression Struct-column surface)
    "unnest",
    "struct_to_dict",
    # Library path
    "LIB",
]
