"""Generate _polars_statistics.pyi by introspecting the runtime module and
mapping return types from the Rust source signatures.

Run from repo root with the built extension importable:
    .venv/bin/python scripts/gen_stubs.py
"""
import inspect
import re
from pathlib import Path

import polars_statistics._polars_statistics as mod

SRC = Path("src/pymodels")

RUST_TO_PY = {
    "f64": "float",
    "Option<f64>": "float | None",
    "usize": "int",
    "i64": "int",
    "u32": "int",
    "bool": "bool",
    "()": "None",
    "String": "str",
    "Bound<'py, PyArray1<f64>>": "numpy.ndarray",
    "Bound<'py, PyArray2<f64>>": "numpy.ndarray",
    "Bound<'py, PyArray1<bool>>": "numpy.ndarray",
    "Option<Bound<'py, PyArray1<f64>>>": "numpy.ndarray | None",
    "Bound<'py, PyDict>": "dict",
    "Vec<Bound<'py, PyDict>>": "list[dict]",
    "PyAidResult": '"AidResult"',
}

name_re = re.compile(r'#\[pyclass\s*\(\s*name\s*=\s*"([^"]+)"', re.S)
fn_start_re = re.compile(r"\bfn\s+([a-z_0-9]+)(?:<[^>]*>)?\s*\(")


def match_paren(text, open_idx):
    """Given index of '(', return index just after matching ')'."""
    depth = 0
    i = open_idx
    while i < len(text):
        c = text[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    return len(text)


def strip_self_ret(ret, class_name):
    ret = ret.strip()
    if ret.startswith("PyResult<") and ret.endswith(">"):
        ret = ret[len("PyResult<") : -1].strip()
    # Self / PyRef / PyRefMut of Self -> the class itself
    if ret == "Self" or ret.endswith("Self") or "Self>" in ret:
        return f'"{class_name}"'
    return RUST_TO_PY.get(ret, "Any")


class_method_ret = {}
global_method_ret = {}

for rs in sorted(SRC.glob("py_*.rs")):
    text = rs.read_text()
    pyclass_names = name_re.findall(text)
    primary = pyclass_names[0] if pyclass_names else rs.stem
    for m in fn_start_re.finditer(text):
        name = m.group(1)
        open_paren = m.end() - 1
        after_args = match_paren(text, open_paren)
        rest = text[after_args:]
        brace = rest.find("{")
        seg = rest[: brace if brace != -1 else len(rest)]
        ret_raw = seg.split("->", 1)[1].strip() if "->" in seg else "()"
        pyann = strip_self_ret(ret_raw, primary)
        for cn in pyclass_names:
            class_method_ret.setdefault(cn, {})[name] = pyann
        global_method_ret.setdefault(name, pyann)


def clean_params(ts):
    ts = ts.strip().replace("$self", "self").replace("$cls", "cls")
    if ts.startswith("("):
        ts = ts[1:]
    if ts.endswith(")"):
        ts = ts[:-1]
    return ts.strip()


lines = [
    "# This file is auto-generated by scripts/gen_stubs.py. Do not edit by hand.",
    "# Regenerate after changing src/pymodels/*.rs:",
    "#     .venv/bin/maturin develop && .venv/bin/python scripts/gen_stubs.py",
    "# ruff: noqa",
    "from typing import Any",
    "",
    "import numpy",
    "",
]

classes = [
    (a, getattr(mod, a))
    for a in sorted(dir(mod))
    if not a.startswith("_") and inspect.isclass(getattr(mod, a))
]

for cname, cls in classes:
    ret_map = class_method_ret.get(cname, {})
    lines.append(f"class {cname}:")
    body = []

    init_ts = getattr(cls, "__text_signature__", None)
    if init_ts:
        params = clean_params(init_ts)
        if params:
            body.append(f"    def __init__(self, {params}) -> None: ...")
        else:
            body.append("    def __init__(self) -> None: ...")

    for mname in sorted(dir(cls)):
        if mname.startswith("__"):
            continue
        st = inspect.getattr_static(cls, mname, None)
        live = getattr(cls, mname, None)
        kind = type(st).__name__
        ret = ret_map.get(mname, global_method_ret.get(mname, "Any"))
        if kind == "getset_descriptor":
            body.append("    @property")
            body.append(f"    def {mname}(self) -> {ret}: ...")
        elif kind == "method_descriptor" or callable(live):
            ts = getattr(live, "__text_signature__", None)
            if ts:
                params = clean_params(ts)
                if not params.startswith("self"):
                    params = ("self, " + params) if params else "self"
                body.append(f"    def {mname}({params}) -> {ret}: ...")
            else:
                body.append(f"    def {mname}(self, *args: Any, **kwargs: Any) -> {ret}: ...")
        else:
            body.append(f"    {mname}: Any")

    if not body:
        body.append("    ...")
    lines.extend(body)
    lines.append("")

out = Path("python/polars_statistics/_polars_statistics.pyi")
out.write_text("\n".join(lines) + "\n")
print(f"Wrote {out} with {len(classes)} classes")
